#!/bin/sh

# configure keys
key1="a"
key2="b"
key3="c"
key4="d"

# configure processes (procX gets triggered by keyX)
# every process must end with `pkill terminator`
proc1() {
    pkill terminator
}
proc2() {
    pkill terminator
}
proc3() {
    pkill terminator
}
proc4() {
    pkill terminator
}

# save original stty settings
settings=$(stty -g)
stty raw -echo

while :;
do
    byte=$(dd bs=1 count=1 2> /dev/null)    # read keys

    # select process to run
    case $byte in
        $key1)
            proc1 &
            ./terminator $!
            ;;
        $key2)
            proc2 &
            ./terminator $!
            ;;
        $key3)
            proc3 &
            ./terminator $!
            ;;
        $key4)
            proc4 &
            ./terminator $!
            ;;
    esac
done

# reload original stty settings
stty "$settings"