#!/bin/sh

pid="$1"

while :;
do
    byte=$(read newline)            # use read, dd clogs up input

    if [ "$byte" = "\n" ]; then
        kill "$pid"
        printf "killed $pid"
        break
    fi
done